### ISSUE TITLE
Accidental export of api keys

### ISSUE THREAD

**Issue by nibirrayy** [L04DB4L4NC3R/DEC#7]
I don't use joplin notes but you have accidentally uploaded a copy of your zshrc with joplin api keys just pointing that out
@L04DB4L4NC3R

**Comment by L04DB4L4NC3R** [comment]
Thanks for pointing it out. I'm aware of this. The API key is used for other local services to interact with your local Joplin instance. They have no link with cloud sync. Plus they can also be regenerated, so it's not an issue.
